SonarSource/sonar-scanner-python

.github/workflows/build-pr.yml, pyproject.toml, src/py_sonar_scanner/configuration.py
Due to missing coverage, the quality gate is obviously red.
I believe this should be fixed in later PRs.
=> PYSCAN-33: Setup SonarCloud analysis

src/pysonar_scanner/configuration.py
- **PYSCAN-69 Rename scanner to pysonar-scanner**
- **PYSCAN-70 Update sonar-scanner-cli version to 6.0.0.4432**
=> PYSCAN-70 Update sonar-scanner-cli version to 6.0.0.4432

.github/PULL_REQUEST_TEMPLATE.md, .github/workflows/PullRequestClosed.yml, .github/workflows/PullRequestCreated.yml, .github/workflows/RequestReview.yml, .github/workflows/SubmitReview.yml
[SCANPY-81](https://sonarsource.atlassian.net/browse/SCANPY-81)
To review:
Make sure the files are the same as these
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestClosed.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/PullRequestCreated.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/RequestReview.yml
https://github.com/SonarSource/sonar-dotnet-enterprise/blob/master/.github/workflows/SubmitReview.yml
https://raw.githubusercontent.com/SonarSource/sonar-dotnet-enterprise/refs/heads/master/.github/PULL_REQUEST_TEMPLATE.md?token=GHSAT0AAAAAACM3Q6EYDU5DNCGFOFCNBMAYZYSOQXA
Make sure that PullRequestCreated.yml has the correct Jira project on the last line
FYI: …
=> SCANPY-81 Add Jira integration

.github/renovate.json
[SCANPY-88](https://sonarsource.atlassian.net/browse/SCANPY-88)
Part of 
[SCANPY-88]: https://sonarsource.atlassian.net/browse/SCANPY-88?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-88 Enable only major, minor and patch updates in renovate

.github/renovate.json, poetry.lock, pyproject.toml
[SCANPY-90](https://sonarsource.atlassian.net/browse/SCANPY-90)
Part of 
[SCANPY-90]: https://sonarsource.atlassian.net/browse/SCANPY-90?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-90 Update PyTest version to 8.3.4

.github/workflows/PullRequestCreated.yml
[SCANPY-92](https://sonarsource.atlassian.net/browse/SCANPY-92)
Part of 
[SCANPY-92]: https://sonarsource.atlassian.net/browse/SCANPY-92?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-92 Disabling Jira tickets creation for renovate

.cirrus.yml, .cirrus/poetry.Dockerfile
[SCANPY-97](https://sonarsource.atlassian.net/browse/SCANPY-97)
- **Pin poetry version to 2.0.1 and migrate pyproject.toml for PEP 621**
- **Migrate dockerfile to uv**
[SCANPY-97]: https://sonarsource.atlassian.net/browse/SCANPY-97?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-97 Migrate build container to use uv

its/poetry.lock, its/pyproject.toml, poetry.lock, pyproject.toml
[SCANPY-76](https://sonarsource.atlassian.net/browse/SCANPY-76)
Part of 
[SCANPY-76]: https://sonarsource.atlassian.net/browse/SCANPY-76?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-76: Set Repox as primary source in Poetry source config

.cirrus.yml
[SCANPY-93](https://sonarsource.atlassian.net/browse/SCANPY-93)
[SCANPY-93]: https://sonarsource.atlassian.net/browse/SCANPY-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-93 Switch from SonarQube Cloud to SonarQube Server NEXT instance

.github/workflows/PullRequestClosed.yml, src/pysonar_scanner/configuration.py
[SCANPY-110](https://sonarsource.atlassian.net/browse/SCANPY-110)
[SCANPY-110]: https://sonarsource.atlassian.net/browse/SCANPY-110?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-110 Support all scanner engine properties

.cirrus.yml, .cirrus/analysis.sh, sonar-project.properties
[SCANPY-93](https://sonarsource.atlassian.net/browse/SCANPY-93)
[SCANPY-93]: https://sonarsource.atlassian.net/browse/SCANPY-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-93 Externalize SQ analysis and make sure branches are fetch

poetry.lock, pyproject.toml, src/pysonar_scanner/api.py, src/pysonar_scanner/cache.py, src/pysonar_scanner/configuration.py, src/pysonar_scanner/exceptions.py, src/pysonar_scanner/scannerengine.py, src/pysonar_scanner/utils.py, tests/sq_api_utils.py, tests/test_api.py, tests/test_cache.py, tests/test_scannerengine.py, tests/test_utils.py
[SCANPY-101](https://sonarsource.atlassian.net/browse/SCANPY-101)
[SCANPY-101]: https://sonarsource.atlassian.net/browse/SCANPY-101?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-101: New bootstrapping: Fetch the Scanner Engine

sonar-project.properties
[SCANPY-93](https://sonarsource.atlassian.net/browse/SCANPY-93)
[SCANPY-93]: https://sonarsource.atlassian.net/browse/SCANPY-93?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-93 Fix project name on SQ Next

src/pysonar_scanner/configuration.py, tests/test_configuration.py
[SCANPY-126](https://sonarsource.atlassian.net/browse/SCANPY-126)
[SCANPY-126]: https://sonarsource.atlassian.net/browse/SCANPY-126?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-126 Serialize the scanner properties to JSON

src/pysonar_scanner/api.py, src/pysonar_scanner/cache.py, src/pysonar_scanner/exceptions.py, src/pysonar_scanner/jre.py, src/pysonar_scanner/utils.py, tests/sq_api_utils.py, tests/test_api.py, tests/test_cache.py, tests/test_jre.py, tests/test_scannerengine.py, tests/test_utils.py
[SCANPY-100](https://sonarsource.atlassian.net/browse/SCANPY-100)
Part of 
[SCANPY-100]: https://sonarsource.atlassian.net/browse/SCANPY-100?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-100: New bootstrapping: Resolve the JRE to use

pyproject.toml, sonar-project.properties
[SCANPY-144](https://sonarsource.atlassian.net/browse/SCANPY-144)
[SCANPY-144]: https://sonarsource.atlassian.net/browse/SCANPY-144?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-144 Setup v1.0

src/pysonar_scanner/configuration/cli.py, tests/test_configuration_cli.py
[SCANPY-130](https://sonarsource.atlassian.net/browse/SCANPY-130)
[SCANPY-130]: https://sonarsource.atlassian.net/browse/SCANPY-130?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-130 Accept options of the form -Dsonar.***

pyproject.toml, scripts/generate_licenseheaders.sh, src/pysonar_scanner/configuration/__init__.py, src/pysonar_scanner/configuration/properties.py, src/pysonar_scanner/configuration/properties_file.py, src/pysonar_scanner/configuration/sonar_project_properties.py, tests/test_configuration.py, tests/test_properties_file.py, tests/test_sonar_project_properties.py
[SCANPY-146](https://sonarsource.atlassian.net/browse/SCANPY-146)
[SCANPY-146]: https://sonarsource.atlassian.net/browse/SCANPY-146?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-146 Parse properties from sonar-project.properties file

src/pysonar_scanner/configuration/environment_variables.py, tests/test_configuration_loader.py, tests/test_environment_variables.py
[SCANPY-115](https://sonarsource.atlassian.net/browse/SCANPY-115)
[SCANPY-115]: https://sonarsource.atlassian.net/browse/SCANPY-115?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-115 Parse the scanner properties from the generic environnement variables

src/pysonar_scanner/__main__.py, src/pysonar_scanner/jre.py, src/pysonar_scanner/scannerengine.py, tests/unit/test_main.py, tests/unit/test_scannerengine.py
[SCANPY-155](https://sonarsource.atlassian.net/browse/SCANPY-155)
[SCANPY-155]: https://sonarsource.atlassian.net/browse/SCANPY-155?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-155 Provide properties computed during bootstrapping to the scanner engine

src/pysonar_scanner/configuration/cli.py, src/pysonar_scanner/configuration/properties.py, tests/unit/test_configuration_cli.py
[SCANPY-138](https://sonarsource.atlassian.net/browse/SCANPY-138)
[SCANPY-138]: https://sonarsource.atlassian.net/browse/SCANPY-138?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-138 Support python custom analyzer properties

.cirrus.yml, tests/unit/test_main.py, tests/unit/test_scannerengine.py
[SCANPY-129](https://sonarsource.atlassian.net/browse/SCANPY-129)
[SCANPY-129]: https://sonarsource.atlassian.net/browse/SCANPY-129?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-129 Add a CI task to run the tests on a windows machine

src/pysonar_scanner/configuration/cli.py, src/pysonar_scanner/configuration/properties.py, tests/unit/test_configuration_cli.py
[SCANPY-161](https://sonarsource.atlassian.net/browse/SCANPY-161)
Part of SCANPY-98
[SCANPY-161]: https://sonarsource.atlassian.net/browse/SCANPY-161?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-161 add Python report related properties to cli

src/pysonar_scanner/api.py, src/pysonar_scanner/configuration/cli.py, src/pysonar_scanner/configuration/configuration_loader.py, src/pysonar_scanner/configuration/environment_variables.py, src/pysonar_scanner/configuration/pyproject_toml.py, src/pysonar_scanner/scannerengine.py
[SCANPY-135](https://sonarsource.atlassian.net/browse/SCANPY-135)
Part of 
[SCANPY-135]: https://sonarsource.atlassian.net/browse/SCANPY-135?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-135 remove useless import to app_logging

src/pysonar_scanner/configuration/cli.py, src/pysonar_scanner/configuration/properties.py, tests/unit/test_configuration_cli.py
[SCANPY-167](https://sonarsource.atlassian.net/browse/SCANPY-167)
[SCANPY-167]: https://sonarsource.atlassian.net/browse/SCANPY-167?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-167 add sonar.organization property

src/pysonar_scanner/api.py, src/pysonar_scanner/jre.py, src/pysonar_scanner/scannerengine.py, tests/its/test_minimal.py, tests/unit/sq_api_utils.py, tests/unit/test_api.py, tests/unit/test_jre.py, tests/unit/test_scannerengine.py
[SCANPY-166](https://sonarsource.atlassian.net/browse/SCANPY-166)
[SCANPY-166]: https://sonarsource.atlassian.net/browse/SCANPY-166?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-166 Ensure the JRE is downloaded properly when the US region is set

pyproject.toml
[SCANPY-169](https://sonarsource.atlassian.net/browse/SCANPY-169)
[SCANPY-169]: https://sonarsource.atlassian.net/browse/SCANPY-169?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-169 Prepare for next development iteration

.cirrus.yml, poetry.lock, pyproject.toml, sonar-project.properties, src/pysonar_scanner/__main__.py, src/pysonar_scanner/api.py, src/pysonar_scanner/configuration/cli.py, src/pysonar_scanner/configuration/configuration_loader.py, src/pysonar_scanner/configuration/dynamic_defaults_loader.py, src/pysonar_scanner/configuration/properties.py, src/pysonar_scanner/configuration/pyproject_toml.py, src/pysonar_scanner/jre.py, src/pysonar_scanner/scannerengine.py, src/pysonar_scanner/utils.py, tests/unit/test_api.py, tests/unit/test_scannerengine.py
[SCANPY-160](https://sonarsource.atlassian.net/browse/SCANPY-160)
[SCANPY-160]: https://sonarsource.atlassian.net/browse/SCANPY-160?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-160 add mypy to the ci

sonar-project.properties
[SCANPY-172](https://sonarsource.atlassian.net/browse/SCANPY-172)
[SCANPY-172]: https://sonarsource.atlassian.net/browse/SCANPY-172?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-172 project version should be read from 'pyproject.toml'

.cirrus.yml, .cirrus/analysis.sh
[SCANPY-173](https://sonarsource.atlassian.net/browse/SCANPY-173)
[SCANPY-173]: https://sonarsource.atlassian.net/browse/SCANPY-173?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-173 Use pysonar instead of pysonar-scanner

.cirrus.yml
[SCANPY-175](https://sonarsource.atlassian.net/browse/SCANPY-175)
[SCANPY-175]: https://sonarsource.atlassian.net/browse/SCANPY-175?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-175 Do not set build version when analyzing

src/pysonar_scanner/app_logging.py, tests/unit/test_app_logging.py
[SCANPY-180](https://sonarsource.atlassian.net/browse/SCANPY-180)
[SCANPY-180]: https://sonarsource.atlassian.net/browse/SCANPY-180?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-180 Non-error logs should not be sent to stderr

README.md
[SCANPY-174](https://sonarsource.atlassian.net/browse/SCANPY-174)
Part of 
[SCANPY-174]: https://sonarsource.atlassian.net/browse/SCANPY-174?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-174: Fix README typos and license year

README.md
[SCANPY-68](https://sonarsource.atlassian.net/browse/SCANPY-68)
Part of 
[SCANPY-68]: https://sonarsource.atlassian.net/browse/SCANPY-68?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-68: Redirect user feedback to Community forums

.cirrus.yml, .cirrus/run_iris.sh
[SCANPY-202](https://sonarsource.atlassian.net/browse/SCANPY-202)
[SCANPY-202]: https://sonarsource.atlassian.net/browse/SCANPY-202?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
=> SCANPY-202 Enable IRIS issue propagation to SQC-EU/US
