SonarSource/sonar-scanner-python

- src/py_sonar_scanner/__main__.py
- src/py_sonar_scanner/configuration.py
- tests/test_configuration.py
Add test for jvm argument parsing.
Make passing of arguments clear.
Revert usage of sys.argv.
> PYSCAN-2: Add tests for the args parsing.

- src/py_sonar_scanner/configuration.py
I have just changed the implementation here, and there are deliberately no tests associated because these will be done as part of PYSCAN-3.
> PYSCAN-31 Correct Configuration to look for the  table instead of the table in pyproject.toml

- src/py_sonar_scanner/configuration.py
- tests/resources/test_toml_file.toml
- tests/test_configuration.py
Right now I just do dictionary parsing. Therefore it remains for me to write tests to check that toml files get mapped correctly to dicts. 
Also, I don't look at how it interacts with the CLI arguments. I will take care of that later today. I nonetheless appreciate any review of the current tests. Thanks in advance!
> PYSCAN-3 Add tests for pyproject.toml file parsing.

- src/py_sonar_scanner/configuration.py
- tests/test_configuration.py
In the `sonar-scanner-cli`, CLI arguments take precedence over the ones located in `sonar-project.properties` files. Also when duplicated CLI arguments are provided, the last one to be defined takes precedence over the older ones.
Because arguments derived from `pyproject.toml` files are passed from the wrapper to the `sonar-scanner-cli` as command line arguments, they will naturally take precedence over the ones in `sonar-project.properties`. Since only arguments under the `tool.sonar` key are considered, this should provide a good user experience.
To ensure CLI arguments to the wrapper keep their precedence over `pyproject.toml` ones, they are passed last to the `sonar-scanner-cli`.
We might want to revisit this logic if we decide to derive analysis properties from other elements from …
> PYSCAN-41 Implement and test handling of duplicate arguments

- .gitignore
So here I decided to omit any virtual environment created in the `its` directory, as per the ticket description. Another way would of course be to ignore any environment created in any subdirectory. Essentially replacing the `its` with `*`. Would this make more sense perhaps? LMKWYT.
> PYSCAN-51 Add the virtual environment created specifically for the integration tests to the .gitignore.

- .cirrus.yml
That way it keeps working (ci-docker-images will no longer produce JDK18 images as it is EOL)
> BUILD-5727 Use JDK21 LTS instead of JDK18 EOL

- .github/workflows/PullRequestCreated.yml
[SONARPY-87](https://sonarsource.atlassian.net/browse/SONARPY-87)
Part of 
[SONARPY-87]: https://sonarsource.atlassian.net/browse/SONARPY-87?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SONARPY-87: Configure Github action to not create Jira tickets for renovate PRs

- .cirrus.yml
[SCANPY-118](https://sonarsource.atlassian.net/browse/SCANPY-118)
Part of SCANPY-98
[SCANPY-118]: https://sonarsource.atlassian.net/browse/SCANPY-118?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANPY-118 Use functioning py-sonar-scanner instead of the branch version

- .github/workflows/releasability.yml
[SCANPY-75](https://sonarsource.atlassian.net/browse/SCANPY-75)
This PR introduces the releasability check in the sonar-scanner-python repository. Unfortunately, the releasability GitHub action doesn't fully support python projects (see [PREQ-456](https://sonarsource.atlassian.net/browse/PREQ-465)) and, therefore, the `CheckManifestValues` check has to be ignored as it always fails.
See [this](https://github.com/SonarSource/sonar-scanner-python/actions/runs/13994360330/job/39185620439) successful pipeline run.
Also, note: this pipeline still uses the ubuntu-latest runner instead of the sonar-runner. The sonar-scanner-python project hasn't been on boarded yet to use the new runenrs. However, this should be done as part of [SCANPY-154](https://sonarsource.atlassian.net/browse/SCANPY-154) …
> SCANPY-75: Added releasability task to CI

- src/pysonar_scanner/configuration/configuration_loader.py
- src/pysonar_scanner/configuration/environment_variables.py
- src/pysonar_scanner/configuration/properties.py
- tests/test_configuration_loader.py
- tests/test_environment_variables.py
- tests/test_properties.py
[SCANPY-114](https://sonarsource.atlassian.net/browse/SCANPY-114)
Note: this is based on SCANPY-139 branch, which probably should be reviewed first (although both changes can be reviewed independently - the goal is to avoid merge conflicts).
[SCANPY-114]: https://sonarsource.atlassian.net/browse/SCANPY-114?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANPY-114 Parse the scanner properties from the environnement variables

- src/pysonar_scanner/__main__.py
- src/pysonar_scanner/cache.py
- tests/unit/sq_api_utils.py
- tests/unit/test_cache.py
- tests/unit/test_jre.py
- tests/unit/test_scannerengine.py
[SCANPY-151](https://sonarsource.atlassian.net/browse/SCANPY-151)
[SCANPY-151]: https://sonarsource.atlassian.net/browse/SCANPY-151?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANPY-151 Fix cache location for the Python scanner

- src/pysonar_scanner/api.py
- src/pysonar_scanner/exceptions.py
- tests/unit/test_api.py
[SCANPY-120](https://sonarsource.atlassian.net/browse/SCANPY-120)
Used the following implementation as a reference:
https://github.com/SonarSource/sonar-scanner-java-library/blob/7556a8f71999ad457ac77ec2416b1d837539b478/lib/src/main/java/org/sonarsource/scanner/lib/internal/endpoint/ScannerEndpointResolver.java#L37
Tests:
https://github.com/SonarSource/sonar-scanner-java-library/blob/7556a8f71999ad457ac77ec2416b1d837539b478/lib/src/test/java/org/sonarsource/scanner/lib/internal/endpoint/ScannerEndpointResolverTest.java#L139
[SCANPY-120]: https://sonarsource.atlassian.net/browse/SCANPY-120?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANPY-120 Use the new region URLs

- .cirrus.yml
- .cirrus/run_its.sh
- .cirrus/run_macos_tests.sh
[SCANPY-78](https://sonarsource.atlassian.net/browse/SCANPY-78)
Since the macOS workers are only available during business hours (and even then in limited capacity), it makes more sense to run the macOS ITs as a "nightly" job in the morning. I've created the following cron job.
[SCANPY-78]: https://sonarsource.atlassian.net/browse/SCANPY-78?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANPY-78 CI Pipeline should test our scanner on a macos VM

- src/pysonar_scanner/__main__.py
- src/pysonar_scanner/api.py
- src/pysonar_scanner/configuration/cli.py
- src/pysonar_scanner/configuration/configuration_loader.py
- src/pysonar_scanner/exceptions.py
- src/pysonar_scanner/jre.py
- src/pysonar_scanner/scannerengine.py
- tests/its/test_minimal.py
- tests/unit/test_configuration_loader.py
- tests/unit/test_exceptions.py
- tests/unit/test_main.py
The following list shows the different error messages that will be shown in different scenarios.
* Missing parameters
* invalid token
* SQ Version too old
* Invalid region
* invalid checksum
* invalid CLI arg
When `--verbose` is passed (or debug logging is activated through another mechanism), the stack trace is shown as well. Unfortunately, this doesn't work for missing cli args, since the exception is thrown before the logging can be configured.
> SCANPY-149 Provide useful error message in case an exception is raised

- pyproject.toml
Bumping to `1.01` as we need to perform a new release with the updated README so that the package description on PyPI is not misleading.
> SCANPY-165 Prepare for next development iteration

- .cirrus.yml
- CLI_ARGS.md
- README.md
- src/pysonar_scanner/configuration/cli.py
- tools/generate_cli_documentation.py
[SCANPY-156](https://sonarsource.atlassian.net/browse/SCANPY-156)
[SCANPY-156]: https://sonarsource.atlassian.net/browse/SCANPY-156?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANPY-156 Expand documentation for the pysonar-scanner

- .cirrus.yml
- src/pysonar_scanner/jre.py
- src/pysonar_scanner/utils.py
- tests/unit/test_utils.py
[SCANPY-181](https://sonarsource.atlassian.net/browse/SCANPY-181)
So far, pysonar has used the `filter` parameter of `tarfile.extractall(...)`, which was introduced in Python 3.12. However, the parameter was backported to 3.9.17, 3.10.12, 3.11.4, which all released on 06.06.2023. Because we used up to date Python versions, which had the backport, in our ITs, they didn't fail and we didn't notice.
[SCANPY-181]: https://sonarsource.atlassian.net/browse/SCANPY-181?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANPY-181 Only use the the filter parameter of tarfile.extractall if supported

- src/pysonar_scanner/configuration/environment_variables.py
- src/pysonar_scanner/configuration/properties.py
- src/pysonar_scanner/scannerengine.py
- tests/test_environment_variables.py
- tests/unit/test_scannerengine.py
[SCANPY-178](https://sonarsource.atlassian.net/browse/SCANPY-178)
Part of 
[SCANPY-178]: https://sonarsource.atlassian.net/browse/SCANPY-178?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANPY-178: The scanner should respect the SONAR_SCANNER_OPTS environment variable

- src/pysonar_scanner/configuration/cli.py
[SCANPY-190](https://sonarsource.atlassian.net/browse/SCANPY-190)
Part of 
[SCANPY-190]: https://sonarsource.atlassian.net/browse/SCANPY-190?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANPY-190 Group command line arguments

- .cirrus.yml
[SCANPY-194](https://sonarsource.atlassian.net/browse/SCANPY-194)
[SCANPY-194]: https://sonarsource.atlassian.net/browse/SCANPY-194?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANPY-194 Repair Mend scan

- src/pysonar_scanner/__main__.py
- tests/unit/test_main.py
[SCANPY-54](https://sonarsource.atlassian.net/browse/SCANPY-54)
Part of 
[SCANPY-54]: https://sonarsource.atlassian.net/browse/SCANPY-54?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANPY-54: Running a scan displays a message to point the user to different Sonar product

- .cirrus.yml
- .cirrus/analysis.sh
- sonar-project.properties
[SCANPY-201](https://sonarsource.atlassian.net/browse/SCANPY-201)
[SCANPY-201]: https://sonarsource.atlassian.net/browse/SCANPY-201?atlOrigin=eyJpIjoiNWRkNTljNzYxNjVmNDY3MDlhMDU5Y2ZhYzA5YTRkZjUiLCJwIjoiZ2l0aHViLWNvbS1KU1cifQ
> SCANPY-201 Enable analysis on both SQC instances
